### ISSUE TITLE
Subissue: Frontend 2 - Add dining commons table to Home Page

### ISSUE THREAD

**Issue by Refinnej04** [ucsb-cs156-f24/proj-dining-f24-14#13]
# User Story

* As a user
* I can see a list of all of the dining commons on the home page so that navigate to their individual pages in an organized simple manner.
* Their subpages will have more capabilities and functions to filter dates and meal types to then get to a final menu based on those specifications where I can review the specific item offered.

## Frontend 2: Add dining commons table to Home Page

Add the dining commons table to the home page, along with code to query the backend  `GET /api/diningcommons/all` and display the results in the table.   Each dining commons code should link to the page `/diningcommons/:diningCommonsCode`

**Comment by pconrad** [comment]
@Refinnej04 please update this issue to be specific about which of these five original issues it comes from: https://github.com/ucsb-cs156-f24/proj-dining-f24-14/issues/39 https://github.com/ucsb-cs156-f24/proj-dining-f24-14/issues/40 https://github.com/ucsb-cs156-f24/proj-dining-f24-14/issues/41 https://github.com/ucsb-cs156-f24/proj-dining-f24-14/issues/42 and/or https://github.com/ucsb-cs156-f24/proj-dining-f24-14/issues/43

Please also improve the description.

In particular, please add a user story to explain *why* we are "[adding] the dining commons table to the home page". 

What is the user story (as a _ I can _ so that _) that is the context for why the user needs to see a table of dining commons locations on the home page?   An issue description needs to contain this information.

And why does each dining commons link to that other page?  What will be at that other page?

This is the context that someone needs to understand how this issue fits into the big picture.   *You* may understand all of that, and you may think that it isn't necessary to write it out if you are the one working on the issue.

But in writing issues, we have to communicate that to everyone else on the team as well.
