### ISSUE TITLE
Subissue: Create database table for reviews

### ISSUE THREAD

**Issue by Va1a** [ucsb-cs156-f24/proj-dining-f24-14#31]
**Inherits from #40** 
Backend 1: Create database table for reviews. The table will have the following fields:
id
Student user id (just the number in the users table)
itemId (ONLY the itemId from the MenuItems table... this picks up the DiningCommons, Meal, MenuItem and Station DiningCommons, Meal, MenuItem and StationName Name from the item table).
Date item was served
Status (initally "Awaiting Moderation")
userid of moderator if approved/rejected (initially null)
Moderator comments (initally null)
CreatedDate
LastEditedDate

**Comment by pconrad** [comment]
@Va1a please update this issue to be specific about which of these five original issues it comes from: #39 #40 #41 #42  and/or #43 

ALSO: This is INCORRECT.  The fields DiningCommons, Meal, Meal Item and Station Name should come from the a join with the Item table on ItemId, not stored redundantly in each review.  This is an important principle of database normalization.

<pre>
id
Student user id (just the number in the users table)
itemId
Date item was served
Status (initally "Awaiting Moderation")
userid of moderator if approved/rejected (initially null)
Moderator comments (initally null)
CreatedDate
LastEditedDate
</pre>


These are the fields that should be eliminated:

<pre>
<s>DiningCommons</s> (redundant because it's represented by itemId)
<s>Meal</s> (redundant because it's represented by itemId)
<s>Meal Item </s> (redundant because it's represented by itemId)
<s>Station Name </s> (redundant because it's represented by itemId)
</pre>
